# Generated by Django 4.1.7 on 2023-03-20 21:40

from django.db import migrations, models
import django.db.models.deletion
import story.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=story.models.get_category_path
                    ),
                ),
                ("description", models.TextField(default="", max_length=500)),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default, 1-Trending"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-default, 1-Hidden"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=story.models.get_product_path
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                ("original_price", models.FloatField()),
                ("selling_price", models.FloatField()),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-defauld, 1-Trending"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-default, 1-Hidden"),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        default=True, help_text="is the product in stock"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="story.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="story.category"
                    ),
                ),
                (
                    "specifications",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.specifications",
                    ),
                ),
            ],
        ),
    ]
