# Generated by Django 4.1.7 on 2023-03-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_remove_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="brand",
            name="name",
            field=models.CharField(default="default value", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specifications",
            name="amount_of_speeds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="specifications",
            name="frame_size",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="specifications",
            name="material",
            field=models.CharField(
                choices=[
                    ("Алюміній", "Алюміній"),
                    ("Карбон", "Карбон"),
                    ("Сталь", "Сталь"),
                    ("Хром-Молібден (CrMo)", "Хром-Молібден (CrMo)"),
                ],
                default="default value",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specifications",
            name="type_of_brakes",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="specifications",
            name="wheel_diameter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="story.specifications"
            ),
        ),
    ]
