# Generated by Django 4.1.7 on 2023-03-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0005_alter_cart_user"),
    ]

    operations = [
        migrations.DeleteModel(name="Cart",),
    ]
