# Generated by Django 4.1.7 on 2023-04-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0009_alter_orderitem_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="product_name", new_name="product",
        ),
    ]
