# Generated by Django 4.1.7 on 2023-04-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0010_rename_product_name_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="subtotal",),
    ]
