# Generated by Django 4.1.7 on 2023-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0013_feedback_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="rating", field=models.FloatField(default=0),
        ),
    ]
